### ISSUE TITLE
default deployment bucket

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/template-kaskadi-lambda#2]
> SLS_DEPLOY_BUCKET: this is the bucket where the Serverless build should be uploaded at deployment.

as we now have our single-deployment-bucket in place, we should default to that bucket when SLS_DEPLOY_BUCKET is missing

**Comment by alexlemaire** [comment]
I added this environment variable to not expose the name of our deployment bucket to remove potential attack vectors.

Defaulting it would go against this, I don't know if that's ok for you (because the name would then be visible somewhere in the code)

**Comment by alexlemaire** [comment]
Closing for now to cleanup open issues. If this is still an issue we can reopen and speak about it again :smile:
